# # Here the delivery is done immediately when the after the pull request is merged into main.
name: Bloggy CD
on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ptlvaibhav/blog-demo-app
      IMAGE_TAG: build-${{github.run_number}}
    
    steps:
      - name: Checkout the source  code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 .
      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Push docker image to Docker Hub
        run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}